runtime: python311
service: neo-ai-tutor

env_variables:
  STREAMLIT_SERVER_PORT: "8080"
  STREAMLIT_SERVER_ADDRESS: "0.0.0.0"
  STREAMLIT_SERVER_HEADLESS: "true"
  STREAMLIT_SERVER_ENABLE_CORS: "false"
  STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION: "false"

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10

entrypoint: streamlit run MATTHSos.py --server.port=8080 --server.address=0.0.0.0

handlers:
  - url: /.*
    script: auto
    secure: always

inbound_services:
  - warmup

instance_class: F2 